### ISSUE TITLE
`datetime.timedelta` Raise Exception

### ISSUE THREAD

**Issue by hanxifu** [gaogaotiantian/codesnap#1]
python version: 3.8.5
Run with python -m script.py arg1 arg2

Before scripts:
```
Exception ignored in: <module 'collections.abc' from '/usr/lib/python3.8/collections/abc.py'>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "xxx/lib/python3.8/site-packages/codesnap/tracer.py", line 37, in tracer
    name = "{}.{}{}".format(frame.f_globals['__name__'], class_name, frame.f_code.co_name)
KeyError: '__name__'
<frozen importlib._bootstrap>:219: RuntimeWarning: Cython module failed to patch module with custom type
```

After scripts:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "xxx/lib/python3.8/site-packages/codesnap/__main__.py", line 21, in <module>
    snap.save()
  File "xxx/lib/python3.8/site-packages/codesnap/codesnap.py", line 20, in save
    self.parse()
  File "xxx/lib/python3.8/site-packages/codesnap/tracer.py", line 50, in parse
    self.snaptree.add_exit(data[1], data[2])
  File "xxx/lib/python3.8/site-packages/codesnap/snaptree.py", line 38, in add_exit
    raise Exception("Function Entry/Exit did not match.{} vs {}", name, self.curr.function_name)
Exception: ('Function Entry/Exit did not match.{} vs {}', 'datetime.timedelta.__new__', 'datetime.__new__')
```

**Comment by hanxifu** [comment]
Another mistake. last line exception. `.format(x, y)` or `f''`

**Comment by gaogaotiantian** [comment]
Hi,

Could you make a minimum script that can reproduce this error? Also what interpreter are you using? Is it CPython or something less common? Did you use Cython? I have never tested the module with Cython. 

The Exception string is a valid mistake, thanks!

**Comment by hanxifu** [comment]
Sorry here's a late reply. Just back to the office.

I‘m using CPython 3.8.5 and here's the simplest reproducible script.

```python3
# test.py
from datetime import timedelta

a = timedelta(hours=5)
```

reproduce steps:

1. `python -m codesnap test.py`
2. Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fuhanxi/.local/share/virtualenvs/ci-dashboard-NLA6c-je/lib/python3.8/site-packages/codesnap/__main__.py", line 21, in <module>
    snap.save()
  File "/home/fuhanxi/.local/share/virtualenvs/ci-dashboard-NLA6c-je/lib/python3.8/site-packages/codesnap/codesnap.py", line 20, in save
    self.parse()
  File "/home/fuhanxi/.local/share/virtualenvs/ci-dashboard-NLA6c-je/lib/python3.8/site-packages/codesnap/tracer.py", line 50, in parse
    self.snaptree.add_exit(data[1], data[2])
  File "/home/fuhanxi/.local/share/virtualenvs/ci-dashboard-NLA6c-je/lib/python3.8/site-packages/codesnap/snaptree.py", line 38, in add_exit
    raise Exception("Function Entry/Exit did not match.{} vs {}", name, self.curr.function_name)
Exception: ('Function Entry/Exit did not match.{} vs {}', 'datetime.timedelta.__new__', 'datetime.__new__')
```

I didn't look into your code, but I guess the `datetime` library is using some trick. Maybe you can take a look at it?

**Comment by hanxifu** [comment]
Sorry here's a late reply. Just back to the office.

I‘m using CPython 3.8.5 and here's the simplest reproducible script.

```python3
# test.py
from datetime import timedelta

a = timedelta(hours=5)
```

reproduce steps:

1. `python -m codesnap test.py`
2. Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "xxx/lib/python3.8/site-packages/codesnap/__main__.py", line 21, in <module>
    snap.save()
  File "xxx/lib/python3.8/site-packages/codesnap/codesnap.py", line 20, in save
    self.parse()
  File "xxx/lib/python3.8/site-packages/codesnap/tracer.py", line 50, in parse
    self.snaptree.add_exit(data[1], data[2])
  File "xxx/lib/python3.8/site-packages/codesnap/snaptree.py", line 38, in add_exit
    raise Exception("Function Entry/Exit did not match.{} vs {}", name, self.curr.function_name)
Exception: ('Function Entry/Exit did not match.{} vs {}', 'datetime.timedelta.__new__', 'datetime.__new__')
```

I didn't look into your code, but I guess the `datetime` library is using some trick. Maybe you can take a look at it?

**Comment by gaogaotiantian** [comment]
This is a valid bug. 

The problem is that when a class has a class method like ```__new__``` or sometimes ```_create```, it will create the ```self``` variable in the method. CodeSnap check against class name via ```self``` to match the name of entry and exit. 

This bug is fixed in [master](https://github.com/gaogaotiantian/codesnap/commit/b8db8897b9d4f84f7438350beb97e75b20d44aab) by ignoring the unmatch when the only difference is class name. This test case will also cause a segfault with c tracer, which is fixed in the same commit. 

A regression test is added.

**Comment by hanxifu** [comment]
I‘ve tested with `pip install -U git+https://github.com/gaogaotiantian/codesnap`, the fix seems worked! Thanks for your effort. I'm closing this issue
